project:
  name: quickstart-boomi-molecule
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    BoomiAccountID: override
    BoomiPassword: override
    BoomiUsername: override
    HostedZoneID: override
    KeyPairName: override
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    RemoteAccessCIDR: 127.0.0.1/32
tests:
  quickstart-boomi-molecule:
    regions:
      - us-east-2
    parameters:
      MoleculeFQDN: override
    template: templates/boomi-molecule-master.template.yaml
